server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin-authority-service
          uri: lb://ADMIN-AUTHORITY-SERVICE
          predicates:
            - Path=/admin/api/v1/authority/**